doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                driver:   pdo_mysql
                host:     '%env(MYSQL_ADDON_HOST)%'
                port:     '%env(MYSQL_ADDON_PORT)%'
                dbname:   '%env(MYSQL_ADDON_DB)%'
                user:     '%env(MYSQL_ADDON_USER)%'
#                password: '%env(MYSQL_ADDON_PASSWORD)%'
                charset:  UTF8
                profiling: "%kernel.debug%"
                server_version: '%env(MYSQL_ADDON_VERSION)%'
                mapping_types:
                    uuid_binary: binary
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Config:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Config/Model'
                prefix: 'App\Config\Model'
                alias: Config
            Editorial:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Editorial/Domain/Model'
                prefix: 'App\Editorial\Domain\Model'
                alias: Editorial

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
