version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3308:3306"
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
